baseURL: https://theindieweb.com
languageCode: en-us
title: The Indie Web
permalinks:
  posts: /:slug
  category: /:slug
  tags: /tag/:slug

paginate: 10
paginatePath: ''

taxonomies:
  category: category
  tag: tags

outputs:
  page:
    - HTML

outputFormats:
  rss:
    baseName: feed

markup:
  highlight:
    style: monokailight
    guessSyntax: true